app:
  name: springboot-jwt-demo
jwt:
  header: Authorization
  expires_in: 30000
  mobile_expires_in: 600
  secret: queenvictoria
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      exclude: src/main/resources/**
server:
  port: 9090
